on:
  push:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install project dependencies
        shell: bash
        run: |
          brew install --cask multipass
          hash -r
      - name: Wait for multipass to be up
        shell: bash
        run: |
          until multipass list; do
            echo 'multipass is not running, will check again in 5 seconds'
            sleep 5
          done
      - name: Download source
        uses: actions/checkout@v2
      - name: Create ENV
        run: cp env.dist env
      - name: Create VM
        run: ./install.sh
      - name: Stop VM
        run: ./stop.sh
      - name: Start VM
        run: ./start.sh
      - name: Destroy VM
        run: ./uninstall.sh
